set(CMAKE_CXX_FLAGS "/W3 /EHsc")
set(CMAKE_CXX_FLAGS_DEBUG "/DWIN32 /D_WINDOWS /DEP_COMPILE_DEBUG /Zi /fp:precise /GR- /GS /permissive-")
set(CMAKE_CXX_FLAGS_RELEASE "/DEP_COMPILE_RELEASE /fp:precise /GR- /GS /Ox /Oi")

set(CMAKE_EXE_LINKER_FLAGS "/NOLOGO /DYNAMICBASE")